site_name: Understanding Metadata 
copyright: Copyright © 2026 CLOSER
docs_dir: docs/

theme:
  name: material
  language: en
  features:
#    - navigation.expand
    - navigation.prune  # use this to collapse twhen more than one module is live
    - content.tooltips
  logo: assets/closer.png
  font:
    text: Source Sans Pro  
  palette:
    primary: purple  
  nav:
    Introductory course: 
      - Getting started: "introduction/1.0 Module Introduction.md"
      
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
    lang: 
      - en
      - fr      
  - i18n:
    docs_structure: suffix 
    languages:
      - locale: 'en'
        default: true
        name: English
        build: true
      - locale: 'fr'
        name: Francais
        build: true
        nav_translations:        
          Introductory course: Cours d'introduction
          Getting started: Mise en route

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
  analytics:
    provider: google
    property: G-XM55ZQ1426
  
