site_name: Understanding Metadata 
copyright: Copyright © 2026 CLOSER
docs_dir: docs/

theme:
  language: en
  name: material
  features:
#    - navigation.expand
    - navigation.prune  # use this to collapse twhen more than one module is live
    - content.tooltips
  logo: assets/closer.png
  font:
    text: Source Sans Pro  
  palette:
    primary: purple    
  nav:
    - Introductory course: index.md
     - Getting started: 
       - "introduction/1.0 Module Introduction.md"
#    - 1.1 Research Data: "introduction/1.1 Research data.md"
#    - 1.2 Research Data Management: "introduction/1.2 Research data management.md"
#    - 1.3 FAIR: "introduction/1.3 FAIR.md"
#    - 2.1 Introduction to Metadata: "introduction/2.1 Introduction to metadata.md"
#    - 2.2 Metadata in the Research Data Lifecycle: "introduction/2.2 Metadata in the research lifecycle.md"
#    - 2.3 Using Metadata: "introduction/2.3 Using metadata - discover data.md"
#    - 2.4 Controlled Vocabularies: "introduction/2.4 Controlled vocabularies.md"
#    - 2.5 Metadata Standards: "introduction/2.5 Metadata standards.md"
#    - 3.0 Metadata activity: "introduction/activity.md"
#    - 4.0 Summary: "introduction/2.7 Introduction summary.md"  
#  - Foundation course: 
#    - Overview: "foundation/0 F_overview_planning.md"
#    - Getting started: "foundation/0. Getting started.md"
#    - Introduction: "foundation/1.0  Introduction.md"
#    - 1.1 Who should Create Metadata?: "foundation/1.1 Who should create metadata.md"
#    - 1.2 Why Metadata Matters: "foundation/1.2 Why metadata matters.md"
#    - 2.0 Core Metadata: "foundation/2.0 Core metadata elements.md"
#    - 2.1 Unit Type, Population and Universe: "foundation/2.1 Unit type, Population and Universe.md"
#    - 2.2 Data Collection Metadata: "foundation/2.2 Data collection metadata.md"
#    - 2.3 Question and Measurement Metadata: "foundation/2.3 Question and measurement metadata.md"
#    - 2.4 Codes and Category Metadata: "foundation/2.4 Codes and category metadata.md"
#    - 2.5 Variable Metadata: "foundation/2.5 Variable metadata.md"
#    - 2.6 Concept Metadata: "foundation/2.6 Concept metadata.md"
#    - 2.7 Study Metadata: "foundation/2.7 Study metadata.md"  
#    - 2.8 Dataset Metadata: "foundation/2.8 Dataset metadata.md"  
#    - 3.0 Metadata Relationships: "foundation/3. Metadata relationships.md"  
#    - 4.1 Considerations for what Metadata to Create: "foundation/4.1 Considerations for what metadata to create.md"  
#    - 4.2 How to Create Metadata: "foundation/4.2 How to create metadata.md"  
#    - 5.1 Activity - Create Study Metadata: "foundation/Activity: Create study metadata.md"  
#    - 5.2 Activity - Create Metadata Relationships: "foundation/Activity: Create metadata relationships.md"  
#  - Resources: "resources.md"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      
extra_css:
  - stylesheets/extra.css

plugins:
  - i18n:
      docs_structure: suffix 
      default_language: 'en'
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: Francais
          build: true
        - nav_translations:
            Introductory course: Cours d'introduction
            Getting started: Mise en route

extra:
  analytics:
    provider: google
    property: G-XM55ZQ1426
  
